// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//   ucd-generate property-bool /home/farhan/Projects/tokenizer/regexr/data/.ucd-temp/ucd-17.0.0 --include whitespace
//
// Unicode version: 17.0.0.
//
// ucd-generate 0.3.1 is available on crates.io.

pub const BY_NAME: &'static [(&'static str, &'static [(u32, u32)])] = &[
  ("White_Space", WHITE_SPACE),
];

pub const WHITE_SPACE: &'static [(u32, u32)] = &[
  (9, 13), (32, 32), (133, 133), (160, 160), (5760, 5760), (8192, 8202),
  (8232, 8233), (8239, 8239), (8287, 8287), (12288, 12288),
];
